services:
  mariadb:
    image: mariadb:10
    container_name: alertbox-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: alertbox_org_dev
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: alertbox-redis
    restart: unless-stopped
    command: redis-server --requirepass masterpass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "masterpass", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: oven/bun:1.3-alpine
    container_name: alertbox-api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: alertbox.org.dev
      DB_PASS: "dev-super-secure-password"
      DB_NAME: alertbox_org_dev
      DB_MIGRATION_USER: alertbox_migrator_dev
      DB_MIGRATION_PASS: "dev-migration-very-secure-password"
      DB_MIGRATION_SHADOW_NAME: alertbox_org_dev_shadow
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_SENTINEL_ENABLED: "false"
      REDIS_PASSWORD: masterpass
    command: sh -c "bun install && bun x prisma db push && bun run dev"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mariadb_data:
  redis_data:

