import { Prisma } from "@/generated/prisma/client";

export const sessionUserSelect = {
  id: true,
  name: true,
  displayname: true,
  uri: true,
  email: true,
  avatar: true,
  banner: true,
  disabled: true,
  deleted: true,
  create_with: true,
  time: true,
  uri_cooldown: true,
  bio: true,
  published: true,
  social_discord: true,
  social_facebook: true,
  social_reddit: true,
  social_twitchtv: true,
  social_twitter: true,
  social_youtube: true,
  secret: false,
  bmac_secret: false,
  ffp_secret: false,
  kofi_secret: false,
  stripe_secret: false,
} as const satisfies Prisma.accountsSelect;
