import Elysia, { t } from "elysia";
import { Webhook } from "@/classes/webhook";

export const endpoint = new Elysia().post(
  "/kofi",
  async ({ body, set }: any) => {
    const res = await Webhook.kofi.handle(body);
    set.status = res.status;
    return res.body;
  },
  {
    detail: {
      tags: ["Webhooks & Ingestion"],
      summary: "Ingest Ko-fi donation webhook",
      description:
        "Public webhook endpoint for Ko-fi donation and subscription alerts. Set your Ko-fi webhook URL to `https://api.alertbox.org/v1/webhook/kofi`. Matches `verification_token` against creator credentials, deduplicates events, and triggers real-time OBS overlay broadcasts.",
    },
    body: t.Object(
      {
        verification_token: t.Optional(
          t.String({
            description: "Verification token configured in your Ko-fi dashboard.",
            examples: ["abcd-1234-efgh-5678"],
          }),
        ),
        message_id: t.Optional(
          t.String({
            description: "Unique message ID generated by Ko-fi.",
            examples: ["e4eaaaf2-d142-11e1-b3e4-080027620cdd"],
          }),
        ),
        timestamp: t.Optional(
          t.String({
            description: "ISO timestamp of the event.",
            examples: ["2026-09-19T10:00:00Z"],
          }),
        ),
        type: t.Optional(
          t.String({
            description: "Event type (e.g. Donation, Subscription, Commission, Shop Order).",
            examples: ["Donation"],
          }),
        ),
        from_name: t.Optional(
          t.String({
            description: "Supporter display name.",
            examples: ["Alex"],
          }),
        ),
        message: t.Optional(
          t.String({
            description: "Optional donation message from the supporter.",
            examples: ["Keep up the great streams!"],
          }),
        ),
        amount: t.Optional(
          t.Union([t.String(), t.Number()], {
            description: "Donation amount.",
            examples: ["5.00"],
          }),
        ),
        currency: t.Optional(
          t.String({
            description: "3-letter currency code.",
            examples: ["USD"],
          }),
        ),
        kofi_transaction_id: t.Optional(
          t.String({
            description: "Ko-fi payment transaction reference.",
            examples: ["12345678-abcd-1234-abcd-1234567890ab"],
          }),
        ),
      },
      {
        additionalProperties: true,
        description: "Ko-fi webhook payload",
        examples: [
          {
            verification_token: "abcd-1234-efgh-5678",
            message_id: "e4eaaaf2-d142-11e1-b3e4-080027620cdd",
            timestamp: "2026-09-19T10:00:00Z",
            type: "Donation",
            from_name: "Alex",
            message: "Keep up the great streams!",
            amount: "5.00",
            currency: "USD",
            kofi_transaction_id: "12345678-abcd-1234-abcd-1234567890ab",
          },
        ],
      },
    ),
    response: {
      200: t.String({
        description: "Webhook received and processed.",
        examples: ["OK"],
      }),
    },
  },
);

export default endpoint;
